#!/usr/bin/env python3
"""Write bench/results/MANIFEST.md: what produced every raw result file.

A table of numbers is only auditable if a reader can get from a cell back to the
process that made it. This lists every JSON in bench/results/ with the driver
that wrote it, the host and the pins in force.
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
RESULTS = ROOT / "bench" / "results"

DRIVERS = {
    "s1-": ("spikes/s1-keccak", "cargo run --release -p s1-keccak"),
    "s2-": ("spikes/s2-advice", "cargo run --release -p s2-advice -- BYTES"),
    "s6-": ("spikes/s6-trace", "cargo run --release -p s6-trace -- LOG2BOUND"),
    "guest-": ("crates/jolt-eth-host", "scripts/campaign.sh analyze / prove"),
    "sp1-": ("sp1-baseline", "scripts/campaign-sp1.sh execute"),
    "prove-timings": ("scripts/collect-prove-timings.py", "from the campaign log"),
}


def driver(name):
    for prefix, value in DRIVERS.items():
        if name.startswith(prefix):
            return value
    return ("?", "?")


def main():
    lines = [
        "# Manifest",
        "",
        "Generated by `scripts/manifest.py`. Pins are in `../../UPSTREAM.md`;",
        "every Jolt number is `jolt-prover-legacy` at `915faf4`.",
        "",
        "| file | produced by | command | host |",
        "|---|---|---|---|",
    ]
    for path in sorted(RESULTS.glob("*.json")):
        try:
            with path.open() as handle:
                data = json.load(handle)
        except json.JSONDecodeError:
            continue
        host = ""
        if isinstance(data, dict):
            host = data.get("host") or (data.get("env") or {}).get("host", "")
        crate, command = driver(path.name)
        lines.append(f"| `{path.name}` | `{crate}` | `{command}` | {host} |")
    (RESULTS / "MANIFEST.md").write_text("\n".join(lines) + "\n")
    print(f"wrote {RESULTS / 'MANIFEST.md'}")


if __name__ == "__main__":
    main()
